/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h" //Generated by CubeMX, and declares your peripheral handles and pin macros (OLED_RES_Pin, B1_Pin, etc.)

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include <string.h> //buffer handling and command parsing (strlen, strncpy, memset, strcmp)
#include <stdio.h> //used to format numbers into text before sending over UART or drawing on the OLED (snprinf)
#include "bme280.h" //Bosch's vendor-supplied platform-independent driver
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
//ST HAL structures representing the configured peripherals
I2C_HandleTypeDef hi2c1;
SPI_HandleTypeDef hspi1;
UART_HandleTypeDef huart2;

/* USER CODE BEGIN PV */
static struct bme280_dev bme280_device; //Holds calibration data, interface type, and function pointers to my glue code
static uint8_t bme280_i2c_address = BME280_I2C_ADDR_PRIM; //0x76, SDO pin is tied low
static uint8_t bme280_initialized = 0;

static struct bme280_data latest_sensor_data; //read by OLED and UART

static uint32_t last_sample_time_ms = 0;
static uint32_t sample_interval_ms = 1000;

static uint8_t sample_valid = 0;


#define UART_COMMAND_BUFFER_SIZE 64U //preprocessor macro, longest command is "stream off", U = unsigned int

static uint8_t uart_rx_byte;
static char uart_command_buffer[UART_COMMAND_BUFFER_SIZE];
static volatile uint16_t uart_command_index = 0;
static volatile uint8_t uart_command_ready = 0;

/* UART streaming state */
static uint8_t stream_enabled = 0U; //1 means periodic UART sensor output is enabled.0 means streaming is disabled.
static uint32_t last_stream_time_ms = 0U;//Time of the most recent streamed UART output.
static uint32_t stream_interval_ms = 1000U;//Print one stored sample every 1000 ms while streaming is enabled.

/*
 * OLED framebuffer.
 * 128 x 64 monochrome pixels:
 * 128 * 64 = 8192 pixels
 * Each byte stores 8 pixels:
 * 8192 / 8 = 1024 bytes
 */
static uint8_t oled_buffer[1024];

/*Controls how often the OLED is refreshed.The BME280 may still be sampled independently.*/
static uint32_t last_oled_update_ms = 0U;
static uint32_t oled_update_interval_ms = 1000U;
/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_SPI1_Init(void);
/* USER CODE BEGIN PFP */
/* USER CODE BEGIN PFP */

static void UART_Print(const char *message);
static void I2C_Scan(void);
static void BME280_ReadChipID(void);


static BME280_INTF_RET_TYPE STM32_BME280_Read(
    uint8_t reg_addr,
    uint8_t *reg_data,
    uint32_t length,
    void *intf_ptr);

static BME280_INTF_RET_TYPE STM32_BME280_Write(
    uint8_t reg_addr,
    const uint8_t *reg_data,
    uint32_t length,
    void *intf_ptr);

static void STM32_BME280_DelayUs(
    uint32_t period,
    void *intf_ptr);

static int8_t BME280_AppInit(void);

static void BME280_SamplingProcess(void);

static void UART_CommandProcess(void);

static void BME280_PrintStoredSample(void);
static void BME280_StreamingProcess(void);
static void PrintSystemStatus(void);

static void OLED_Reset(void);
static HAL_StatusTypeDef OLED_WriteCommand(uint8_t command);
static HAL_StatusTypeDef OLED_WriteData(uint8_t *data, uint16_t length);
static HAL_StatusTypeDef OLED_Init(void);
static void OLED_FillTest(void);
static void OLED_Clear(void);
static void OLED_UpdateScreen(void);
static void OLED_SetPixel(uint8_t x, uint8_t y);
static void OLED_DrawChar(uint8_t x, uint8_t y, char character);
static void OLED_DrawString(uint8_t x, uint8_t y, const char *text);
static void OLED_DisplaySensorData(void);
static void OLED_Process(void);
//static means private, no other source code can call it accidentally

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{

  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/


  /* USER CODE BEGIN Init */
 /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	  HAL_Init();

  /* USER CODE END Init */


  /* USER CODE BEGIN SysInit */
 /* Configure the system clock */
	   SystemClock_Config(); //The F303 runs up to 36 MHz; this setup uses the HSI and PLL to reach the system clock used by the project.


  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_I2C1_Init();
  MX_USART2_UART_Init();
  MX_SPI1_Init();
  /* USER CODE END SysInit */


  /* USER CODE BEGIN 2 */
  const char message[] =
      "\r\n"
      "STM32 UART test working\r\n"
      "BME280 project started\r\n";

  HAL_UART_Transmit(
      &huart2,
      (uint8_t *)message,
      strlen(message),
      HAL_MAX_DELAY
  );

  HAL_Delay(100);

  I2C_Scan();

  HAL_Delay(100);
  BME280_ReadChipID();

  HAL_Delay(100);

  if (BME280_AppInit() == BME280_OK)
  {
      last_sample_time_ms = HAL_GetTick() - sample_interval_ms;
  }

  HAL_StatusTypeDef uart_rx_status;

  uart_rx_status = HAL_UART_Receive_IT(
      &huart2,
      &uart_rx_byte,
      1
  );

  if (uart_rx_status == HAL_OK)
  {
      UART_Print(
          "\r\nUART command reception enabled.\r\n"
          "Type a command and press Enter.\r\n> "
      );
  }
  else
  {
      UART_Print("Failed to start UART reception.\r\n");
  }


  /*
   * Initialize the SPI OLED.
   */
  if (OLED_Init() == HAL_OK)
  {
      UART_Print("OLED initialized successfully.\r\n");

      //OLED_FillTest(); //First visible OLED test. Turn every pixel on.

      //UART_Print("OLED fill test sent.\r\n");
  }
  else
  {
      UART_Print("OLED initialization failed.\r\n");
  }  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */

      BME280_SamplingProcess();
      // BME280_DebugPrintProcess();
      UART_CommandProcess(); //Prints stored samples periodically only when stream_enabled is set.

      BME280_StreamingProcess();
      OLED_Process(); //Refresh local OLED display once per second.
  }
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL9;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV1;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART2|RCC_PERIPHCLK_I2C1;
  PeriphClkInit.Usart2ClockSelection = RCC_USART2CLKSOURCE_PCLK1;
  PeriphClkInit.I2c1ClockSelection = RCC_I2C1CLKSOURCE_HSI;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_I2C1_Init(void)
{

  /* USER CODE BEGIN I2C1_Init 0 */

  /* USER CODE END I2C1_Init 0 */

  /* USER CODE BEGIN I2C1_Init 1 */

  /* USER CODE END I2C1_Init 1 */
  hi2c1.Instance = I2C1;
  hi2c1.Init.Timing = 0x00201D2B;
  hi2c1.Init.OwnAddress1 = 0;
  hi2c1.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  hi2c1.Init.OwnAddress2 = 0;
  hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
  hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  hi2c1.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&hi2c1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Analogue filter
  */
  if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure Digital filter
  */
  if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN I2C1_Init 2 */

  /* USER CODE END I2C1_Init 2 */

}

/**
  * @brief SPI1 Initialization Function
  * @param None
  * @retval None
  */
static void MX_SPI1_Init(void)
{

  /* USER CODE BEGIN SPI1_Init 0 */

  /* USER CODE END SPI1_Init 0 */

  /* USER CODE BEGIN SPI1_Init 1 */

  /* USER CODE END SPI1_Init 1 */
  /* SPI1 parameter configuration*/
  hspi1.Instance = SPI1;
  hspi1.Init.Mode = SPI_MODE_MASTER;
  hspi1.Init.Direction = SPI_DIRECTION_2LINES;
  hspi1.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
  hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
  hspi1.Init.NSS = SPI_NSS_SOFT;
  hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_32;
  hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi1.Init.TIMode = SPI_TIMODE_DISABLE;
  hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi1.Init.CRCPolynomial = 7;
  hspi1.Init.CRCLength = SPI_CRC_LENGTH_DATASIZE;
  hspi1.Init.NSSPMode = SPI_NSS_PULSE_ENABLE;
  if (HAL_SPI_Init(&hspi1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN SPI1_Init 2 */

  /* USER CODE END SPI1_Init 2 */

}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  huart2.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
  huart2.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* USER CODE BEGIN MX_GPIO_Init_1 */

  /* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOF_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(GPIOB, OLED_RES_Pin|OLED_DC_Pin|OLED_CS_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin */
  GPIO_InitStruct.Pin = B1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pins : OLED_RES_Pin OLED_DC_Pin OLED_CS_Pin */
  GPIO_InitStruct.Pin = OLED_RES_Pin|OLED_DC_Pin|OLED_CS_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

  /* USER CODE BEGIN MX_GPIO_Init_2 */

  /* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */
static void UART_Print(const char *message)
{
    if (message == NULL)
    {
        return;
    }

    HAL_UART_Transmit(
        &huart2,
        (uint8_t *)message,
        strlen(message),
        HAL_MAX_DELAY
    );
}

static void I2C_Scan(void)
{
    char message[64];
    uint8_t devices_found = 0;

    UART_Print("\r\nStarting I2C scan...\r\n");

    for (uint16_t address = 1; address < 128; address++) //loop starts at 1 rather than address 0x00 as that's reserved General Call address
    {
        HAL_StatusTypeDef result;

        result = HAL_I2C_IsDeviceReady(
            &hi2c1, //I2C peripheral handle
            address << 1, //STM32 HAL expects the 7-bit address shifted into the address byte position
            3, //How many times to retry the handshake before giving up on this address
            20 //Max milliseconds to wait for a response, per trial
        );
// 127 × 3 × 20 ms ≈ 7.6 seconds, slow loop, runs once at boot in the main()
        if (result == HAL_OK)
        {
            snprintf(
                message,
                sizeof(message),
                "Device found at address 0x%02X\r\n",
                address
            );

            UART_Print(message);
            devices_found++;
        }
    }

    if (devices_found == 0)
    {
        UART_Print("No I2C devices found.\r\n");
    }
    else
    {
        snprintf(
            message,
            sizeof(message),
            "Scan complete. Devices found: %u\r\n",
            devices_found
        );

        UART_Print(message);
    }
}

static void BME280_ReadChipID(void)
{
    const uint16_t bme280_address = (0x76 << 1);
    const uint8_t chip_id_register = 0xD0; //id register is at 0xD0 and contains 0x60

    uint8_t chip_id = 0;
    char message[64];

    HAL_StatusTypeDef result;
//Talk to device 0x76, then read internal register 0xD0.
    result = HAL_I2C_Mem_Read(
        &hi2c1,
        bme280_address,
        chip_id_register,
        I2C_MEMADD_SIZE_8BIT,
        &chip_id,
        1,
        100 // <- timeout ceiling, not a fixed delay
    ); //blocking function

    if (result == HAL_OK)
    {
        snprintf(
            message,
            sizeof(message),
            "BME280 chip ID: 0x%02X\r\n",
            chip_id
        );

        UART_Print(message);

        if (chip_id == 0x60)
        {
            UART_Print("Confirmed: BME280 detected.\r\n");
        }
        else
        {
            UART_Print("Unexpected chip ID.\r\n");
        }
    }
    else
    {
        UART_Print("Failed to read BME280 chip ID.\r\n");
    }
}

static BME280_INTF_RET_TYPE STM32_BME280_Read(
    uint8_t reg_addr,
    uint8_t *reg_data,
    uint32_t length,
    void *intf_ptr)
{
    if ((reg_data == NULL) || (intf_ptr == NULL))
    {
        return BME280_E_NULL_PTR;
    }

    uint8_t device_address = *(uint8_t *)intf_ptr;

    HAL_StatusTypeDef status = HAL_I2C_Mem_Read(
        &hi2c1,
        device_address << 1,
        reg_addr,
        I2C_MEMADD_SIZE_8BIT,
        reg_data,
        (uint16_t)length,
        100
    );

    return (status == HAL_OK) ? BME280_INTF_RET_SUCCESS : BME280_E_COMM_FAIL;
}

static BME280_INTF_RET_TYPE STM32_BME280_Write(
    uint8_t reg_addr,
    const uint8_t *reg_data,
    uint32_t length,
    void *intf_ptr)
{
    if ((reg_data == NULL) || (intf_ptr == NULL))
    {
        return BME280_E_NULL_PTR;
    }

    uint8_t device_address = *(uint8_t *)intf_ptr;

    HAL_StatusTypeDef status = HAL_I2C_Mem_Write(
        &hi2c1,
        device_address << 1,
        reg_addr,
        I2C_MEMADD_SIZE_8BIT,
        (uint8_t *)reg_data,
        (uint16_t)length,
        100
    );

    return (status == HAL_OK) ? BME280_INTF_RET_SUCCESS : BME280_E_COMM_FAIL;
}

static void STM32_BME280_DelayUs(
    uint32_t period,
    void *intf_ptr)
{
    (void)intf_ptr;

    uint32_t delay_ms = (period + 999U) / 1000U;

    if (delay_ms == 0U)
    {
        delay_ms = 1U;
    }

    HAL_Delay(delay_ms);
}

static int8_t BME280_AppInit(void)
{
    int8_t result;
    struct bme280_settings settings;

    memset(&bme280_device, 0, sizeof(bme280_device));
    memset(&settings, 0, sizeof(settings));

    bme280_device.intf = BME280_I2C_INTF;
    bme280_device.intf_ptr = &bme280_i2c_address;
    bme280_device.read = STM32_BME280_Read;
    bme280_device.write = STM32_BME280_Write;
    bme280_device.delay_us = STM32_BME280_DelayUs;

    result = bme280_init(&bme280_device);

    if (result != BME280_OK)
    {
        UART_Print("BME280 driver initialization failed.\r\n");
        return result;
    }

    settings.filter = BME280_FILTER_COEFF_OFF;
    settings.osr_h = BME280_OVERSAMPLING_1X;
    settings.osr_p = BME280_OVERSAMPLING_1X;
    settings.osr_t = BME280_OVERSAMPLING_1X;
    settings.standby_time = BME280_STANDBY_TIME_1000_MS;

    result = bme280_set_sensor_settings(
        BME280_SEL_ALL_SETTINGS,
        &settings,
        &bme280_device
    );

    if (result != BME280_OK)
    {
        UART_Print("BME280 settings configuration failed.\r\n");
        return result;
    }

    result = bme280_set_sensor_mode(
        BME280_POWERMODE_NORMAL, // In normal mode it automatically cycles between measurement and standby. FW then periodically reads the most recently available measurement.
        &bme280_device
    );

    if (result != BME280_OK)
    {
        UART_Print("BME280 mode configuration failed.\r\n");
        return result;
    }

    bme280_initialized = 1;
    UART_Print("BME280 initialized successfully.\r\n");

    return BME280_OK;
}

/*
 * @brief verify initialization
 * check whether the interval has elapsed
 * read the latest sensor data
 */
static void BME280_SamplingProcess(void)
{
    if (!bme280_initialized)
    {
        return;
    }

    uint32_t current_time_ms = HAL_GetTick();

    if ((current_time_ms - last_sample_time_ms) < sample_interval_ms)
    {
        return;
    }

    last_sample_time_ms = current_time_ms;

    int8_t result = bme280_get_sensor_data(
        BME280_ALL,
        &latest_sensor_data,
        &bme280_device
    );

    if (result == BME280_OK)
    {
        sample_valid = 1;
    }
    else
    {
        sample_valid = 0;
    }
}

/**
 * @brief UART receive-complete callback, fires once per received byte.
 *
 * Called automatically by the HAL whenever a single byte requested by
 * HAL_UART_Receive_IT() has arrived. Runs in interrupt context.
 *
 * Builds up uart_command_buffer one character at a time until Enter
 * is pressed, then marks uart_command_ready so the main loop can
 * process the completed command in UART_CommandProcess().
 */

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
	/*
	     * This callback is shared across all UART peripherals.
	     * Ignore anything that isn't our console UART.
	     */
	if (huart->Instance != USART2)
    {
        return;
    }

    if ((uart_rx_byte == '\r') || (uart_rx_byte == '\n')) //Checks whether the byte that arrives was just enter
    {
    	 /*
    	         * Only finalize if something was actually typed, and only
    	         * if a previous command isn't still waiting to be consumed.
    	         * Guards against an empty Enter press and against a
    	         * second CR/LF byte re-closing an already-finished command.
    	         */
    	if ((uart_command_index > 0U) && (uart_command_ready == 0U))
        {
            uart_command_buffer[uart_command_index] = '\0';
            uart_command_ready = 1U;
        }
    }
    else if (uart_command_ready == 0U)
    {
    	/*
    	 * Normal character. Only accept it if there's room left,
    	 * reserving the final slot for the null terminator.
         */
        if (uart_command_index < (UART_COMMAND_BUFFER_SIZE - 1U))
        {
            uart_command_buffer[uart_command_index] = (char)uart_rx_byte;
            uart_command_index++;
        }
        else
        {
            uart_command_index = 0U;
        }
    }
        /*
         * If uart_command_ready is already set, incoming characters
         * are dropped here until the main loop consumes the buffer.
         */

        /*
         * Rearm reception for the next byte. Runs on every path through
         * this function, since HAL_UART_Receive_IT() only ever captures
         * one byte before it needs to be requested again.
         */
    HAL_UART_Receive_IT(
        &huart2,
        &uart_rx_byte,
        1
    );
}

/**
 * @brief Processes one completed UART command.
 *
 * UART reception itself is interrupt-driven.
 * The interrupt collects characters and sets uart_command_ready
 * when the user presses Enter.
 *
 * The actual command processing happens here in the main loop.
 */
static void UART_CommandProcess(void)
{
    char local_command[UART_COMMAND_BUFFER_SIZE];

    /*
     * No completed command waiting.
     */
    if (uart_command_ready == 0U)
    {
        return;
    }

    /*
     * The command buffer is shared with the UART RX interrupt.
     * Disable interrupts briefly while copying/resetting it.
     */
    __disable_irq();

    strncpy(
        local_command,
        uart_command_buffer,
        sizeof(local_command)
    );

    /*
     * Guarantee that this is a valid C string.
     */
    local_command[sizeof(local_command) - 1U] = '\0';

    /*
     * Allow the UART interrupt to begin collecting
     * the next command.
     */
    uart_command_index = 0U;
    uart_command_ready = 0U;

    __enable_irq();

    /*
     * Compare the received text with the supported commands.
     */
    if (strcmp(local_command, "help") == 0)
    {
        UART_Print(
            "\r\nAvailable commands:\r\n"
            "  help        - Show this command list\r\n"
            "  sensor      - Print the latest stored sensor reading\r\n"
            "  stream on   - Start periodic sensor output\r\n"
            "  stream off  - Stop periodic sensor output\r\n"
            "  status      - Show current application status\r\n"
        );
    }
    else if (strcmp(local_command, "sensor") == 0)
    {
        /*
         * Print the most recently stored BME280 measurement.
         * This does not trigger a new I2C measurement.
         */
        BME280_PrintStoredSample();
    }
    else if (strcmp(local_command, "stream on") == 0)
    {
        /*
         * Enable periodic UART reporting.
         *
         * Sensor sampling is already running independently.
         */
        stream_enabled = 1U;

        /*
         * Make the first streamed value appear immediately.
         */
        last_stream_time_ms =
            HAL_GetTick() - stream_interval_ms;

        UART_Print(
            "\r\nSensor streaming enabled.\r\n"
        );
    }
    else if (strcmp(local_command, "stream off") == 0)
    {
        /*
         * Stop UART reporting only.
         *
         * BME280_SamplingProcess() continues reading
         * the sensor every second.
         */
        stream_enabled = 0U;

        UART_Print(
            "\r\nSensor streaming disabled.\r\n"
        );
    }
    else if (strcmp(local_command, "status") == 0)
    {
        PrintSystemStatus();
    }
    else
    {
        UART_Print("\r\nUnknown command: ");
        UART_Print(local_command);

        UART_Print(
            "\r\nType 'help' for available commands.\r\n"
        );
    }

    /*
     * Prompt for the next command.
     */
    UART_Print("> ");
}
static void BME280_PrintStoredSample(void)
{
    char message[160];

    /*
     * A sample is valid only after at least one successful sensor read.
     */
    if (sample_valid == 0U)
    {
        UART_Print(
            "\r\nSensor reading is not available yet.\r\n"
        );

        return;
    }

    /*
     * Convert the stored floating-point values into readable text.
     *
     * The Bosch driver returns:
     * - temperature in degrees Celsius
     * - humidity in percent
     * - pressure in pascals
     *
     * Dividing pressure by 100 converts Pa to hPa.
     */
    snprintf(
        message,
        sizeof(message),
        "\r\n"
        "Temperature: %.2f C\r\n"
        "Humidity: %.2f %%\r\n"
        "Pressure: %.2f hPa\r\n",
        latest_sensor_data.temperature,
        latest_sensor_data.humidity,
        latest_sensor_data.pressure / 100.0
    );

    UART_Print(message);
}

/**
 * @brief Periodically prints the latest stored sensor reading.
 *
 * Sensor sampling and UART streaming are independent activities.
 *
 * Sampling continues every second even when streaming is disabled.
 * This function only controls periodic UART reporting.
 */
static void BME280_StreamingProcess(void)
{
    /*
     * Do nothing when streaming has not been enabled by the user.
     */
    if (stream_enabled == 0U)
    {
        return;
    }

    /*
     * Do not print until at least one valid measurement exists.
     */
    if (sample_valid == 0U)
    {
        return;
    }

    uint32_t current_time_ms = HAL_GetTick();

    /*
     * Return immediately until the streaming interval has elapsed.
     *
     * This avoids blocking the main loop with HAL_Delay().
     */
    if ((current_time_ms - last_stream_time_ms) < stream_interval_ms)
    {
        return;
    }

    /*
     * Record when this stream output occurred.
     */
    last_stream_time_ms = current_time_ms;

    /*
     * Print the most recently stored sample.
     */
    BME280_PrintStoredSample();
}

/**
 * @brief Prints the current application status.
 */
static void PrintSystemStatus(void)
{
    char message[256];

    const char *sensor_text;
    const char *sample_text;
    const char *stream_text;

    /*
     * Translate internal application state into
     * human-readable strings.
     */
    sensor_text =
        bme280_initialized ? "READY" : "NOT INITIALIZED";

    sample_text =
        sample_valid ? "YES" : "NO";

    stream_text =
        stream_enabled ? "ON" : "OFF";

    snprintf(
        message,
        sizeof(message),
        "\r\n"
        "System status:\r\n"
        "  Sensor: %s\r\n"
        "  Valid sample: %s\r\n"
        "  Sampling interval: %lu ms\r\n"
        "  Streaming: %s\r\n"
        "  Streaming interval: %lu ms\r\n",
        sensor_text,
        sample_text,
        (unsigned long)sample_interval_ms,
        stream_text,
        (unsigned long)stream_interval_ms
    );

    UART_Print(message);
}

/**
 * @brief Performs a hardware reset of the OLED controller.
 *
 * The RES pin is controlled by a normal GPIO.
 * Pulling RES low resets the OLED controller.
 * Bringing it high allows normal operation again.
 */
static void OLED_Reset(void)
{
    /* Hold reset low. */
    HAL_GPIO_WritePin(
        OLED_RES_GPIO_Port,
        OLED_RES_Pin,
        GPIO_PIN_RESET
    );

    HAL_Delay(20);

    /* Release the OLED from reset. */
    HAL_GPIO_WritePin(
        OLED_RES_GPIO_Port,
        OLED_RES_Pin,
        GPIO_PIN_SET
    );

    HAL_Delay(20);
}

/**
 * @brief Sends one command byte to the OLED over SPI.
 *
 * DC = LOW tells the OLED that the byte is a command.
 * CS = LOW selects the OLED on the SPI bus.
 */
static HAL_StatusTypeDef OLED_WriteCommand(uint8_t command)
{
    HAL_StatusTypeDef status;

    /* Select OLED. */
    HAL_GPIO_WritePin(
        OLED_CS_GPIO_Port,
        OLED_CS_Pin,
        GPIO_PIN_RESET
    );

    /* Command mode. */
    HAL_GPIO_WritePin(
        OLED_DC_GPIO_Port,
        OLED_DC_Pin,
        GPIO_PIN_RESET
    );

    /* Transmit one byte using SPI1. */
    status = HAL_SPI_Transmit(
        &hspi1,
        &command,
        1,
        100
    );

    /* Release OLED. */
    HAL_GPIO_WritePin(
        OLED_CS_GPIO_Port,
        OLED_CS_Pin,
        GPIO_PIN_SET
    );

    return status;
}

/**
 * @brief Sends display data bytes to the OLED.
 *
 * DC = HIGH tells the OLED that the bytes represent display data.
 */
static HAL_StatusTypeDef OLED_WriteData(
    uint8_t *data,
    uint16_t length)
{
    HAL_StatusTypeDef status;

    if ((data == NULL) || (length == 0U))
    {
        return HAL_ERROR;
    }

    /* Select OLED. */
    HAL_GPIO_WritePin(
        OLED_CS_GPIO_Port,
        OLED_CS_Pin,
        GPIO_PIN_RESET
    );

    /* Data mode. */
    HAL_GPIO_WritePin(
        OLED_DC_GPIO_Port,
        OLED_DC_Pin,
        GPIO_PIN_SET
    );

    status = HAL_SPI_Transmit(
        &hspi1,
        data,
        length,
        100
    );

    /* Release OLED. */
    HAL_GPIO_WritePin(
        OLED_CS_GPIO_Port,
        OLED_CS_Pin,
        GPIO_PIN_SET
    );

    return status;
}

/**
 * @brief Initializes the OLED controller for a 128x64 display.
 *
 * The initialization sequence configures:
 * - display OFF during setup
 * - clock settings
 * - multiplex ratio for 64 rows
 * - display offset/start line
 * - internal charge pump
 * - horizontal memory addressing
 * - segment/COM orientation
 * - contrast
 * - pre-charge and VCOM settings
 * - normal display mode
 * - display ON
 */
static HAL_StatusTypeDef OLED_Init(void)
{
    /*
     * Reset the OLED controller first so we start
     * from a known hardware state.
     */
    OLED_Reset();

    /*
     * Display OFF while configuring the controller.
     */
    if (OLED_WriteCommand(0xAE) != HAL_OK)
        return HAL_ERROR;

    /*
     * Set display clock divide ratio / oscillator frequency.
     */
    OLED_WriteCommand(0xD5);
    OLED_WriteCommand(0x80);

    /*
     * Multiplex ratio.
     *
     * 0x3F = 63 decimal.
     * Since counting starts at zero:
     *
     * 0..63 = 64 display rows.
     */
    OLED_WriteCommand(0xA8);
    OLED_WriteCommand(0x3F);

    /*
     * Display offset = 0.
     */
    OLED_WriteCommand(0xD3);
    OLED_WriteCommand(0x00);

    /*
     * Display start line = 0.
     */
    OLED_WriteCommand(0x40);

    /*
     * Enable the internal charge pump.
     */
    OLED_WriteCommand(0x8D);
    OLED_WriteCommand(0x14);

    /*
     * Select horizontal addressing mode.
     *
     * This makes it easy to write the framebuffer
     * sequentially from left to right and top to bottom.
     */
    OLED_WriteCommand(0x20);
    OLED_WriteCommand(0x00);

    /*
     * Segment remap.
     *
     * This controls horizontal display orientation.
     */
    OLED_WriteCommand(0xA1);

    /*
     * COM output scan direction.
     *
     * This controls vertical display orientation.
     */
    OLED_WriteCommand(0xC8);

    /*
     * Configure COM pins for a 128x64 panel.
     */
    OLED_WriteCommand(0xDA);
    OLED_WriteCommand(0x12);

    /*
     * Set contrast.
     */
    OLED_WriteCommand(0x81);
    OLED_WriteCommand(0x7F);

    /*
     * Set pre-charge period.
     */
    OLED_WriteCommand(0xD9);
    OLED_WriteCommand(0xF1);

    /*
     * Set VCOMH deselect level.
     */
    OLED_WriteCommand(0xDB);
    OLED_WriteCommand(0x40);

    /*
     * Entire display follows display RAM contents.
     */
    OLED_WriteCommand(0xA4);

    /*
     * Normal display:
     * 1 bits = illuminated pixels.
     */
    OLED_WriteCommand(0xA6);

    /*
     * Finally turn the display ON.
     */
    if (OLED_WriteCommand(0xAF) != HAL_OK)
        return HAL_ERROR;

    HAL_Delay(100);

    return HAL_OK;
}

/**
 * @brief Fills the entire 128x64 OLED display with ON pixels.
 *
 * A 128x64 monochrome OLED needs:
 *
 * 128 columns × 64 rows = 8192 pixels
 *
 * Each byte contains 8 vertical pixels:
 *
 * 8192 / 8 = 1024 bytes
 *
 * Sending 0xFF means every bit in every byte is 1,
 * therefore every pixel should illuminate.
 */
static void OLED_FillTest(void)
{
    /*
     * One row of display RAM in our transfer buffer.
     *
     * 128 bytes × 8 pixels per byte.
     */
    uint8_t display_line[128];

    /*
     * Set every bit to 1.
     *
     * 0xFF binary = 11111111
     */
    memset(
        display_line,
        0xFF,
        sizeof(display_line)
    );

    /*
     * Define the column address range:
     *
     * 0 through 127.
     */
    OLED_WriteCommand(0x21);
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0x7F);

    /*
     * Define the page address range:
     *
     * Page 0 through Page 7.
     *
     * 8 pages × 8 pixels = 64 vertical pixels.
     */
    OLED_WriteCommand(0x22);
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0x07);

    /*
     * There are 8 pages.
     *
     * Send 128 bytes for each page:
     *
     * 8 × 128 = 1024 bytes total.
     */
    for (uint8_t page = 0; page < 8; page++)
    {
        OLED_WriteData(
            display_line,
            sizeof(display_line)
        );
    }
}


/*
 * Returns one column of a simple 5x7 font.
 *
 * Each character is 5 pixels wide.
 * Each byte represents one vertical column of 7 pixels.
 *
 * We only include the characters required by our display
 * for now. More characters can easily be added later.
 */
static uint8_t OLED_GetFontColumn(char c, uint8_t column)
{
    /*
     * Each row contains the five columns for one character.
     */

    static const uint8_t font_digits[10][5] =
    {
        {0x3E, 0x51, 0x49, 0x45, 0x3E}, /* 0 */
        {0x00, 0x42, 0x7F, 0x40, 0x00}, /* 1 */
        {0x42, 0x61, 0x51, 0x49, 0x46}, /* 2 */
        {0x21, 0x41, 0x45, 0x4B, 0x31}, /* 3 */
        {0x18, 0x14, 0x12, 0x7F, 0x10}, /* 4 */
        {0x27, 0x45, 0x45, 0x45, 0x39}, /* 5 */
        {0x3C, 0x4A, 0x49, 0x49, 0x30}, /* 6 */
        {0x01, 0x71, 0x09, 0x05, 0x03}, /* 7 */
        {0x36, 0x49, 0x49, 0x49, 0x36}, /* 8 */
        {0x06, 0x49, 0x49, 0x29, 0x1E}  /* 9 */
    };

    if ((c >= '0') && (c <= '9'))
    {
        return font_digits[c - '0'][column];
    }


 /* Capital letters and symbols used by our UI.
 *
 * Each case returns one 5-pixel-wide-by-7-pixel-tall glyph, one byte
 * at a time, selected by 'column' (0 to 4). Same encoding as the
 * digit table above: each byte is one vertical column, bit 0 at the
 * top row, bit 6 at the bottom row.
 *
 * Only the characters this project actually displays are defined
 * here. Add more cases the same way if new characters are needed.
 */
    switch (c)
    {
        case 'A':
        {
            static const uint8_t data[5] =
                {0x7E, 0x11, 0x11, 0x11, 0x7E};
            return data[column];
        }

        case 'C':
        {
            static const uint8_t data[5] =
                {0x3E, 0x41, 0x41, 0x41, 0x22};
            return data[column];
        }

        case 'E':
        {
            static const uint8_t data[5] =
                {0x7F, 0x49, 0x49, 0x49, 0x41};
            return data[column];
        }

        case 'H':
        {
            static const uint8_t data[5] =
                {0x7F, 0x08, 0x08, 0x08, 0x7F};
            return data[column];
        }

        case 'I':
        {
            static const uint8_t data[5] =
                {0x00, 0x41, 0x7F, 0x41, 0x00};
            return data[column];
        }

        case 'M':
        {
            static const uint8_t data[5] =
                {0x7F, 0x02, 0x0C, 0x02, 0x7F};
            return data[column];
        }

        case 'N':
        {
            static const uint8_t data[5] =
                {0x7F, 0x04, 0x08, 0x10, 0x7F};
            return data[column];
        }

        case 'O':
        {
            static const uint8_t data[5] =
                {0x3E, 0x41, 0x41, 0x41, 0x3E};
            return data[column];
        }

        case 'P':
        {
            static const uint8_t data[5] =
                {0x7F, 0x09, 0x09, 0x09, 0x06};
            return data[column];
        }

        case 'R':
        {
            static const uint8_t data[5] =
                {0x7F, 0x09, 0x19, 0x29, 0x46};
            return data[column];
        }

        case 'S':
        {
            static const uint8_t data[5] =
                {0x46, 0x49, 0x49, 0x49, 0x31};
            return data[column];
        }

        case 'T':
        {
            static const uint8_t data[5] =
                {0x01, 0x01, 0x7F, 0x01, 0x01};
            return data[column];
        }

        case 'U':
        {
            static const uint8_t data[5] =
                {0x3F, 0x40, 0x40, 0x40, 0x3F};
            return data[column];
        }

        case 'V':
        {
            static const uint8_t data[5] =
                {0x1F, 0x20, 0x40, 0x20, 0x1F};
            return data[column];
        }

        case ':':
        {
            static const uint8_t data[5] =
                {0x00, 0x36, 0x36, 0x00, 0x00};
            return data[column];
        }

        case '.':
        {
            static const uint8_t data[5] =
                {0x00, 0x60, 0x60, 0x00, 0x00};
            return data[column];
        }

        case '%':
        {
            static const uint8_t data[5] =
                {0x63, 0x13, 0x08, 0x64, 0x63};
            return data[column];
        }

        case '-':
        {
            static const uint8_t data[5] =
                {0x08, 0x08, 0x08, 0x08, 0x08};
            return data[column];
        }

        case ' ':
        default:
            return 0x00;
    }
}


/**
 * @brief Clears the local OLED framebuffer.
 *
 * This changes RAM inside the STM32.
 * It does NOT immediately transmit anything to the OLED.
 */
static void OLED_Clear(void)
{
    memset(
        oled_buffer,
        0x00,
        sizeof(oled_buffer)
    );
}


/**
 * @brief Turns one pixel ON in the framebuffer.
 */
static void OLED_SetPixel(uint8_t x, uint8_t y)
{
    /*
     * Reject coordinates outside the 128x64 screen.
     */
    if ((x >= 128U) || (y >= 64U))
    {
        return;
    }

    /*
     * OLED memory is divided into 8-pixel-high pages.
     *
     * y / 8 tells us which page contains this pixel.
     *
     * y % 8 tells us which bit within that page.
     */
    uint16_t index =
        x + ((uint16_t)(y / 8U) * 128U);

    oled_buffer[index] |=
        (1U << (y % 8U));
}


/**
 * @brief Draws one 5x7 character into the framebuffer.
 */
static void OLED_DrawChar(
    uint8_t x,
    uint8_t y,
    char character)
{
    /*
     * Characters are five pixel columns wide.
     */
    for (uint8_t column = 0U; column < 5U; column++)
    {
        uint8_t column_data =
            OLED_GetFontColumn(character, column);

        /*
         * Each column contains seven vertical pixels.
         */
        for (uint8_t row = 0U; row < 7U; row++)
        {
            if (column_data & (1U << row))
            {
                OLED_SetPixel(
                    x + column,
                    y + row
                );
            }
        }
    }
}


/**
 * @brief Draws a null-terminated string.
 */
static void OLED_DrawString(
    uint8_t x,
    uint8_t y,
    const char *text)
{
    if (text == NULL)
    {
        return;
    }

    while (*text != '\0')
    {
        OLED_DrawChar(
            x,
            y,
            *text
        );

        /*
         * Five pixels for the character
         * plus one pixel of spacing.
         */
        x += 6U;

        /*
         * Stop if another character would exceed
         * the display width.
         */
        if (x > 122U)
        {
            break;
        }

        text++;
    }
}


/**
 * @brief Transfers the complete framebuffer to the OLED.
 */
static void OLED_UpdateScreen(void)
{
    /*
     * Select all 128 columns.
     */
    OLED_WriteCommand(0x21);
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0x7F);

    /*
     * Select all eight pages.
     */
    OLED_WriteCommand(0x22);
    OLED_WriteCommand(0x00);
    OLED_WriteCommand(0x07);

    /*
     * Send all 1024 framebuffer bytes.
     */
    OLED_WriteData(
        oled_buffer,
        sizeof(oled_buffer)
    );
}


/**
 * @brief Builds the environmental monitor screen
 *        using the latest stored BME280 measurement.
 */
static void OLED_DisplaySensorData(void)
{
    char line[24];

    /*
     * Don't display measurements until the BME280
     * has produced at least one valid sample.
     */
    if (sample_valid == 0U)
    {
        OLED_Clear();

        OLED_DrawString(
            10,
            20,
            "NO SENSOR DATA"
        );

        OLED_UpdateScreen();

        return;
    }

    /*
     * Start with a blank framebuffer.
     */
    OLED_Clear();

    /*
     * Screen title.
     */
    OLED_DrawString(
        25,
        2,
        "ENV MONITOR"
    );

    /*
     * Temperature.
     */
    snprintf(
        line,
        sizeof(line),
        "TEMP: %.1f C",
        latest_sensor_data.temperature
    );

    OLED_DrawString(
        5,
        18,
        line
    );

    /*
     * Relative humidity.
     */
    snprintf(
        line,
        sizeof(line),
        "HUM: %.1f %%",
        latest_sensor_data.humidity
    );

    OLED_DrawString(
        5,
        30,
        line
    );

    /*
     * Atmospheric pressure.
     *
     * Bosch gives pressure in Pa.
     * Divide by 100 to display hPa.
     */
    snprintf(
        line,
        sizeof(line),
        "PRES: %.0f",
        latest_sensor_data.pressure / 100.0
    );

    OLED_DrawString(
        5,
        42,
        line
    );

    OLED_DrawString(
        80,
        42,
        "HPA"
    );

    /*
     * Push the completed framebuffer to the OLED.
     */
    OLED_UpdateScreen();
}


/**
 * @brief Periodically refreshes the OLED using HAL_GetTick().
 *
 * This follows the same non-blocking scheduling pattern
 * used elsewhere in the application.
 */
static void OLED_Process(void)
{
    uint32_t current_time_ms =
        HAL_GetTick();

    if ((current_time_ms - last_oled_update_ms)
        < oled_update_interval_ms)
    {
        return;
    }

    last_oled_update_ms =
        current_time_ms;

    OLED_DisplaySensorData();
}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
